Controllers/product_classController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using IMODA.Models;

namespace IMODA.Controllers
{
    public class product_classController : Controller
    {
        private test1Entities db = new test1Entities();

        // GET: product_class
        public ActionResult Index()
        {
            return View(db.product_class.ToList());
        }

        // GET: product_class/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            product_class product_class = db.product_class.Find(id);
            if (product_class == null)
            {
                return HttpNotFound();
            }
            return View(product_class);
        }

        // GET: product_class/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: product_class/Create
        // 若要免於過量張貼攻擊，請啟用想要繫結的特定屬性，如需
        // 詳細資訊，請參閱 https://go.microsoft.com/fwlink/?LinkId=317598。
        [HttpPost]

        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "id,c_time,c_id,u_time,u_id,switch,sort,name,banner,banner_url,banner1,banner_url1,banner2,banner_url2,img,img_url,img1,img_url1,img2,img_url2,img3,img_url3,img4,img_url4,banner_action,img_action,index_,remark")] product_class product_class , HttpPostedFileBase file_banner)
        {
            //if (ModelState.IsValid && file_banner != null)
            if (file_banner != null)
            {
                if (file_banner.ContentLength > 0)
                {
                    string path = Path.Combine(Server.MapPath("~/image/product_class/"), file_banner.FileName);
                    file_banner.SaveAs(path);
                }
                product_class.banner = file_banner.FileName;
                db.product_class.Add(product_class);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(product_class);
        }

        // GET: product_class/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            product_class product_class = db.product_class.Find(id);
            if (product_class == null)
            {
                return HttpNotFound();
            }
            return View(product_class);
        }

        // POST: product_class/Edit/5
        // 若要免於過量張貼攻擊，請啟用想要繫結的特定屬性，如需
        // 詳細資訊，請參閱 https://go.microsoft.com/fwlink/?LinkId=317598。
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "id,c_time,c_id,u_time,u_id,switch,sort,name,banner,banner_url,banner1,banner_url1,banner2,banner_url2,img,img_url,img1,img_url1,img2,img_url2,img3,img_url3,img4,img_url4,banner_action,img_action,index_,remark")] product_class product_class)
        {
            if (ModelState.IsValid)
            {
                db.Entry(product_class).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(product_class);
        }

        // GET: product_class/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            product_class product_class = db.product_class.Find(id);
            if (product_class == null)
            {
                return HttpNotFound();
            }
            return View(product_class);
        }

        // POST: product_class/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            product_class product_class = db.product_class.Find(id);
            db.product_class.Remove(product_class);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Views/product_class/Create.cshtml
@model IMODA.Models.product_class

@{
    ViewBag.Title = "Create";
}

<section class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
                <h1>Product > Commodity Pavilion Setting > Add</h1>
            </div>
        </div>
    </div><!-- /.container-fluid -->
</section>

<section class="content">
    <div class="row">
        <div class="col-12">
             
            <div class="card">

                @using (Html.BeginForm("Create", "product_class", FormMethod.Post, new { enctype = "multipart/form-data" }))
                {
                    @Html.AntiForgeryToken()

                <div class="form-horizontal">
                    @*<h4>question_category</h4>*@
                    <hr />
                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                    @Html.HiddenFor(model => model.id)
                    @Html.HiddenFor(model => model.c_id, new { @Value = "1" })
                    @Html.HiddenFor(model => model.u_id, new { @Value = "1" })
                    @Html.HiddenFor(model => model.c_time, new { @Value = DateTime.Now })
                    @Html.HiddenFor(model => model.u_time, new { @Value = DateTime.Now })

                    <div class="form-group">
                        @Html.LabelFor(model => model.@switch, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.@switch, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.@switch, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.sort, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.sort, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.sort, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.name, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.name, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.name, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.banner, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            <input type="file" name="file_banner" /><br />
                            @Html.ValidationMessageFor(model => model.banner, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.banner_url, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.banner_url, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.banner_url, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.banner1, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.banner1, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.banner1, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.banner_url1, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.banner_url1, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.banner_url1, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.banner2, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.banner2, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.banner2, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.banner_url2, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.banner_url2, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.banner_url2, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.img, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.img, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.img, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.img_url, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.img_url, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.img_url, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.img1, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.img1, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.img1, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.img_url1, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.img_url1, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.img_url1, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.img2, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.img2, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.img2, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.img_url2, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.img_url2, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.img_url2, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.img3, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.img3, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.img3, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.img_url3, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.img_url3, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.img_url3, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.img4, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.img4, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.img4, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.img_url4, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.img_url4, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.img_url4, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.banner_action, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.banner_action, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.banner_action, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.img_action, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.img_action, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.img_action, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.index_, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.index_, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.index_, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.remark, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.remark, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.remark, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        <div class="col-md-offset-2 col-md-10">
                            <input type="submit" value="Create" class="btn btn-default" />
                        </div>
                    </div>
                </div>
                }

                <div>
                    @Html.ActionLink("Back to List", "Index")
                </div>
                 
            </div>
             
        </div>
         
    </div>
     
</section>

Views/product_class/Index.cshtml
@model IEnumerable<IMODA.Models.product_class>

@{
    ViewBag.Title = "Index";
}

<section class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
                <h1>Product > Commodity Pavilion Setting</h1>
            </div>
        </div>
    </div><!-- /.container-fluid -->
</section>

<section class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
                <input type="button" class="btn btn-info btn-lg" value="新增" onclick="location.href='@Url.Action("Create", "product_class")'" />
            </div>
        </div>
    </div><!-- /.container-fluid -->
</section>



<section class="content">
    <div class="row">
        <div class="col-12">

            <!-- /.card -->

            <div class="card">
                @*<div class="card-header">
                        <h3 class="card-title">DataTable with default features</h3>
                    </div>*@
                <!-- /.card-header -->
                <div class="card-body">
                    @using (Html.BeginForm("Index", "product_class", FormMethod.Post))
                    {
                        <button type="submit" value="Delete" class="btn btn-sm btn-danger rounded-0" onclick="return confirm('Are you sure?')"><i class="fa fa-trash-o"></i> Delete</button>
                        <br /><br />
                        <table style="text-align:center;" id="example1" class="display">
                            <thead>
                                <tr>

                                    <th>name</th>
                                    <th>show/hidden</th>
                                    <th>index</th>                                   
                                    <th>modify</th>
                                    <th>sort</th>
                                    <th>
                                        select all <input type="checkbox" id="checkBoxAll" class="custom-checkbox" />
                                    </th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach (var item in Model)
                                {
                                    <tr>
                                        <td>
                                            @Html.DisplayFor(modelItem => item.name)
                                        </td>
                                        <td>
                                            @Html.DisplayFor(modelItem => item.@switch)
                                        </td>
                                        <td>
                                            @Html.DisplayFor(modelItem => item.index_)
                                        </td>
                                        
                                        <td>
                                            @Html.ActionLink("modify", "Mod", new { id = item.id })
                                        </td>
                                        <td>
                                            <input name="@item.id" type="text" value="@item.sort">
                                        </td>
                                        <td>
                                            <input type="checkbox" name="ID" value="@item.id" class="custom-checkbox chkCheckBoxId" />
                                        </td>
                                    </tr>
                                }

                            </tbody>
                            <tfoot>
                                <tr>
                                    <th>image</th>
                                    <th>show/hidden</th>
                                    <th>index</th>
                                    <th>modify</th>
                                    <th>sort</th>
                                    <th>select all</th>
                                </tr>
                            </tfoot>
                        </table>
                    }
                </div>
                <!-- /.card-body -->
            </div>
            <!-- /.card -->
        </div>
        <!-- /.col -->
    </div>
    <!-- /.row -->
</section>
<!-- jQuery -->
<script src="~/plugins/jquery/jquery.min.js"></script>
<!-- Bootstrap 4 -->
<script src="../../plugins/bootstrap/js/bootstrap.bundle.min.js"></script>
<!-- DataTables -->
@*<script src="../../plugins/datatables/jquery.dataTables.min.js"></script>*@
<script src="../../plugins/datatables-bs4/js/dataTables.bootstrap4.min.js"></script>
<script src="../../plugins/datatables-responsive/js/dataTables.responsive.min.js"></script>
<script src="../../plugins/datatables-responsive/js/responsive.bootstrap4.min.js"></script>
<script type="text/javascript" src="https://cdn.datatables.net/1.10.21/js/jquery.dataTables.min.js"></script>

<!-- AdminLTE App -->
<script src="../../dist/js/adminlte.min.js"></script>
<!-- AdminLTE for demo purposes -->
<script src="../../dist/js/demo.js"></script>
<!-- page script -->
<script>
    $(document).ready(function () {
        $("#example1").DataTable({
            "paging": true,
            "responsive": true,
            "autoWidth": false,
            "ordering": true,
            "info": true,
            "responsive": true,
        });
        $('#checkBoxAll').click(function () {
            if ($(this).is(":checked")) {
                $(".chkCheckBoxId").prop("checked", true)
            }
            else {
                $(".chkCheckBoxId").prop("checked", false)
            }
        });
    });
</script>