Models/role.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace IMODA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class role
    {
        public int id { get; set; }
        public System.DateTime c_time { get; set; }
        public int c_id { get; set; }
        public System.DateTime u_time { get; set; }
        public int u_id { get; set; }
        public string name { get; set; }
        public string role_class { get; set; }
        public string remark { get; set; }
    }
}

Controllers/roleController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using IMODA.Models;
using IMODA.ViewModels;

namespace IMODA.Controllers
{
    public class roleController : Controller
    {
        private test1Entities db = new test1Entities();

        // GET: roles
        public ActionResult Index()
        {
            return View(db.role.ToList());
        }

        // GET: roles/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            role role = db.role.Find(id);
            if (role == null)
            {
                return HttpNotFound();
            }
            return View(role);
        }

        // GET: roles/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: roles/Create
        // 若要免於過量張貼攻擊，請啟用想要繫結的特定屬性，如需
        // 詳細資訊，請參閱 https://go.microsoft.com/fwlink/?LinkId=317598。
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "id,c_time,c_id,u_time,u_id,name,role_class,remark")] role role)
        {
            if (ModelState.IsValid)
            {
                db.role.Add(role);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(role);
        }
        [ChildActionOnly]
        public ActionResult _Create()
        {
            return PartialView();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult _Create([Bind(Include = "id,c_time,c_id,u_time,u_id,name,role_class,remark")] role role)
        {
            if (ModelState.IsValid)
            {
                db.role.Add(role);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return PartialView(role);
        }



        // GET: roles/Edit/5
        public ActionResult Mod(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            role role = db.role.Find(id);
            var permission = db.permission.OrderBy(m => m.id).ToList();
            if (role == null)
            {
                return HttpNotFound();
            }

            RoleModViewModel viewModel = new RoleModViewModel();
            viewModel.roledata = role;
            viewModel.PermissionsCollection = permission;


            return View(viewModel);
        }

        // POST: roles/Edit/5
        // 若要免於過量張貼攻擊，請啟用想要繫結的特定屬性，如需
        // 詳細資訊，請參閱 https://go.microsoft.com/fwlink/?LinkId=317598。
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Mod([Bind(Include = "ID,roledata,PermissionsCollection")] RoleModViewModel roleModViewModelole)
        {
            if (ModelState.IsValid)
            {
                db.Entry(roleModViewModelole.roledata).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(roleModViewModelole);
        }

        
        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
        [HttpPost]
        public ActionResult Index(FormCollection formCollection)
        {
            string[] ids = formCollection["ID"].Split(new char[] { ',' });
            foreach (string id in ids)
            {
                var role = this.db.role.Find(int.Parse(id));
                this.db.role.Remove(role);
                this.db.SaveChanges();
            }
            return RedirectToAction("Index");
        }


        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            role manger = db.role.Find(id);
            if (manger == null)
            {
                return HttpNotFound();
            }
            return View(manger);
        }

        // POST: manger/Edit/5
        // 若要免於過量張貼攻擊，請啟用想要繫結的特定屬性，如需
        // 詳細資訊，請參閱 https://go.microsoft.com/fwlink/?LinkId=317598。
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "id,c_time,c_id,u_time,u_id,name,role_class,remark")] role role)

        {
            if (ModelState.IsValid)
            {
                db.Entry(role).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(role);
        }
    }
}

Views/role/Index.cshtml
@model IEnumerable<IMODA.Models.role>

@{
    ViewBag.Title = "Index";
}
<section class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
                <h1>Role Management</h1>
            </div>
        </div>
    </div><!-- /.container-fluid -->
</section>
<section class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
                <p>
                    <button type="button" class="btn btn-info btn-lg" data-toggle="modal" data-target="#myModal">新增</button>
                </p>
                @Html.Action("_Create")
            </div>
        </div>
    </div><!-- /.container-fluid -->
</section>
<section class="content">
    <div class="row">
        <div class="col-12">

            <!-- /.card -->

            <div class="card">
                @*<div class="card-header">
                        <h3 class="card-title">DataTable with default features</h3>
                    </div>*@
                <!-- /.card-header -->
                <div class="card-body">
                    @using (Html.BeginForm("Index", "role", FormMethod.Post))
                    {
                        <button type="submit" value="Delete" class="btn btn-sm btn-danger rounded-0" onclick="return confirm('Are you sure?')"><i class="fa fa-trash-o"></i> Delete</button>
                        <br /><br />
                        <table style="text-align:center;" id="example1" class="display">
                            <thead>
                                <tr>

                                    <th>@Html.DisplayNameFor(model => model.name)</th>
                                    <th>modify</th>
                                    <th>select all <input type="checkbox" id="checkBoxAll" class="custom-checkbox" />
                                    </th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach (var item in Model)
                                {
                                    <tr>
                                        <td>
                                            @Html.DisplayFor(modelItem => item.name)
                                        </td>
                                        <td>
                                            @Html.ActionLink("modify", "Mod", new { id = item.id })
                                        </td>
                                        <td>
                                            <input type="checkbox" name="ID" value="@item.id" class="custom-checkbox chkCheckBoxId" />
                                        </td>
                                    </tr>
                                }

                            </tbody>
                            <tfoot>
                                <tr>
                                    <th>@Html.DisplayNameFor(model => model.name)</th>
                                    <th>modify</th>
                                </tr>
                            </tfoot>
                        </table>
                    }
                    </div>
                <!-- /.card-body -->
            </div>
            <!-- /.card -->
        </div>
        <!-- /.col -->
    </div>
    <!-- /.row -->
</section>
<!-- jQuery -->
<script src="~/plugins/jquery/jquery.min.js"></script>
<!-- Bootstrap 4 -->
<script src="../../plugins/bootstrap/js/bootstrap.bundle.min.js"></script>
<!-- DataTables -->
@*<script src="../../plugins/datatables/jquery.dataTables.min.js"></script>*@
<script src="../../plugins/datatables-bs4/js/dataTables.bootstrap4.min.js"></script>
<script src="../../plugins/datatables-responsive/js/dataTables.responsive.min.js"></script>
<script src="../../plugins/datatables-responsive/js/responsive.bootstrap4.min.js"></script>
<script type="text/javascript" src="https://cdn.datatables.net/1.10.21/js/jquery.dataTables.min.js"></script>

<!-- AdminLTE App -->
<script src="../../dist/js/adminlte.min.js"></script>
<!-- AdminLTE for demo purposes -->
<script src="../../dist/js/demo.js"></script>
<!-- page script -->
<script>
    $(document).ready(function () {
        $("#example1").DataTable({
            "paging": true,
            "responsive": true,
            "autoWidth": false,
            "ordering": true,
            "info": true,
            "responsive": true,
        });
        $('#checkBoxAll').click(function () {  
                if ($(this).is(":checked")) {  
                    $(".chkCheckBoxId").prop("checked", true)  
                }  
                else {  
                    $(".chkCheckBoxId").prop("checked", false)  
                }  
        });  
    });
</script>

Views/role/Mod.cshtml
@model IMODA.ViewModels.RoleModViewModel
@{
    ViewBag.Title = "Mod";
}

<section class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
                <h1>Role Management > Modify</h1>
            </div>
        </div>
    </div><!-- /.container-fluid -->
</section>

<section class="content">
    <div class="row">
        <div class="col-12">
            <!-- /.card -->
            <div class="card">
                @*<div class="card-header">
                        <h3 class="card-title">DataTable with default features</h3>
                    </div>*@
                <!-- /.card-header -->
                <div class="card-body">
                    @using (Html.BeginForm())
                    {
                        @Html.AntiForgeryToken()
                    <div class="form-horizontal">
                        @*<h4>Name</h4>*@
                        <hr />
                        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                        @Html.HiddenFor(model => model.ID)
                        @Html.HiddenFor(model => model.roledata.id)
                        @Html.HiddenFor(model => model.roledata.c_time)
                        @Html.HiddenFor(model => model.roledata.c_id)
                        @Html.HiddenFor(model => model.roledata.u_time)
                        @Html.HiddenFor(model => model.roledata.u_id)
                        @Html.HiddenFor(model => model.roledata.role_class , new { @Value = "1" })



                        <div class="form-group">
                            @Html.LabelFor(model => model.roledata.name, htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.EditorFor(model => model.roledata.name, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.roledata.name, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            @Html.LabelFor(model => model.roledata.remark, htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.EditorFor(model => model.roledata.remark, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.roledata.remark, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            @Html.LabelFor(model => model.roledata.role_class, htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @foreach (var item in Model.PermissionsCollection)
                                {
                                    <input type="checkbox" name="role_class" value="@item.id" />@item.name
                                }
                            </div>
                        </div>

                        <div class="form-group">
                            <div class="col-md-offset-2 col-md-10">
                                <input type="submit" value="Save" class="btn btn-default" />
                            </div>
                        </div>
                    </div>
                    }


                </div>
                <!-- /.card-body -->
            </div>
            <!-- /.card -->
        </div>
        <!-- /.col -->
    </div>
    <!-- /.row -->
</section>

<script>
    var array= new Array();
    $(":checkbox").on("change",function(){
        var $checkbox = $(this);
        console.log($('input:checked').length);
        array.push($(this).val());
        //alert(array.join(','));
        $('input[name="roledata.role_class"]').val(array.join(','));
    });

</script>

Views/role/_Create.cshtml
@model IMODA.Models.role
@{
    ViewBag.Title = "Create";
}
    <style>
        .modal-header-primary {
            color: #fff;
            padding: 9px 15px;
            border-bottom: 1px solid #eee;
            background-color: #428bca;
            border-top-left-radius: 5px;
            border-top-right-radius: 5px;
        }

        .modal-footer-primary {
            color: #fff;
            padding: 9px 15px;
            border-top: 1px solid #eee;
            background-color: #428bca;
            border-bottom-left-radius: 5px;
            border-bottom-right-radius: 5px;
        }
    </style>
<!-- Modal -->
@using (Html.BeginForm("_Create", "role"))
{
    @Html.AntiForgeryToken()

    <div id="myModal" class="modal fade" role="dialog">
        <div class="modal-dialog">

            <!-- Modal content-->
            <div class="modal-content">
                <div class="modal-header modal-header-primary">
                    <h4 class="modal-title">Role新增</h4>
                    <button type="button" class="close" aria-label="Close" data-dismiss="modal">&times;</button>

                </div>
                <div class="modal-body">
                    <div class="form-horizontal">
                        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                        <div class="form-group">
                            @Html.LabelFor(model => model.id, htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.EditorFor(model => model.id, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.id, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            @Html.LabelFor(model => model.c_time, htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.EditorFor(model => model.c_time, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.c_time, "", new { @class = "text-danger" })
                            </div>
                        </div>
                        <div class="form-group">
                            @Html.LabelFor(model => model.c_id, htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.EditorFor(model => model.c_id, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.c_id, "", new { @class = "text-danger" })
                            </div>
                        </div>
                        <div class="form-group">
                            @Html.LabelFor(model => model.u_time, htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.EditorFor(model => model.u_time, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.u_time, "", new { @class = "text-danger" })
                            </div>
                        </div>
                        <div class="form-group">
                            @Html.LabelFor(model => model.u_id, htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.EditorFor(model => model.u_id, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.u_id, "", new { @class = "text-danger" })
                            </div>
                        </div>
                        <div class="form-group">
                            @Html.LabelFor(model => model.name, htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                <div class="checkbox">
                                    @Html.EditorFor(model => model.name)
                                    @Html.ValidationMessageFor(model => model.name, "", new { @class = "text-danger" })
                                </div>
                            </div>
                        </div>
                        <div class="form-group">
                            @Html.LabelFor(model => model.role_class, htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                <div class="checkbox">
                                    @Html.EditorFor(model => model.role_class)
                                    @Html.ValidationMessageFor(model => model.role_class, "", new { @class = "text-danger" })
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="modal-footer modal-footer-primary">
                    <button type="submit" class="btn btn-default">Create</button>
                </div>
            </div>
        </div>
    </div>
}