Models/question_category.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace IMODA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class question_category
    {
        public int id { get; set; }
        public int active { get; set; }
        public string en_title { get; set; }
        public string en_content { get; set; }
        public string th_title { get; set; }
        public string th_content { get; set; }
    }
}

Controllers/question_categoryController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using IMODA.Models;

namespace IMODA.Controllers
{
    public class question_categoryController : Controller
    {
        private test1Entities db = new test1Entities();

        // GET: question_category
        public ActionResult Index()
        {
            return View(db.question_category.ToList());
        }
        [HttpPost]
        public ActionResult Index(FormCollection formCollection)
        {
            string[] ids = formCollection["ID"].Split(new char[] { ',' });
            foreach (string id in ids)
            {
                var question_category = this.db.question_category.Find(int.Parse(id));
                this.db.question_category.Remove(question_category);
                this.db.SaveChanges();
            }
            return RedirectToAction("Index");
        }

        // GET: question_category/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            question_category question_category = db.question_category.Find(id);
            if (question_category == null)
            {
                return HttpNotFound();
            }
            return View(question_category);
        }

        // GET: question_category/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: question_category/Create
        // 若要免於過量張貼攻擊，請啟用想要繫結的特定屬性，如需
        // 詳細資訊，請參閱 https://go.microsoft.com/fwlink/?LinkId=317598。
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "id,active,en_title,en_content,th_title,th_content")] question_category question_category)
        {
            if (ModelState.IsValid)
            {
                db.question_category.Add(question_category);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(question_category);
        }

        // GET: question_category/Edit/5
        public ActionResult Mod(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            question_category question_category = db.question_category.Find(id);
            if (question_category == null)
            {
                return HttpNotFound();
            }
            return View(question_category);
        }

        // POST: question_category/Edit/5
        // 若要免於過量張貼攻擊，請啟用想要繫結的特定屬性，如需
        // 詳細資訊，請參閱 https://go.microsoft.com/fwlink/?LinkId=317598。
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Mod([Bind(Include = "id,active,en_title,en_content,th_title,th_content")] question_category question_category)
        {
            if (ModelState.IsValid)
            {
                db.Entry(question_category).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(question_category);
        }

        // GET: question_category/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            question_category question_category = db.question_category.Find(id);
            if (question_category == null)
            {
                return HttpNotFound();
            }
            return View(question_category);
        }

        // POST: question_category/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            question_category question_category = db.question_category.Find(id);
            db.question_category.Remove(question_category);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

    }
}

Views/question_category/Create.cshtml
@model IMODA.Models.question_category

@{
    ViewBag.Title = "Create";
}

<section class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
                <h1>Question Category Management > Add</h1>
            </div>
        </div>
    </div><!-- /.container-fluid -->
</section>

<section class="content">
    <div class="row">
        <div class="col-12">
            <!-- /.card -->
            <div class="card">

                @using (Html.BeginForm())
                {
                    @Html.AntiForgeryToken()

                    <div class="form-horizontal">
                        @*<h4>question_category</h4>*@
                        <hr />
                        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                        

                        <div class="form-group">
                            @Html.LabelFor(model => model.active, htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.EditorFor(model => model.active, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.active, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            @Html.LabelFor(model => model.en_title, htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.EditorFor(model => model.en_title, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.en_title, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            @Html.LabelFor(model => model.en_content, htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @*@Html.EditorFor(model => model.en_content, new { htmlAttributes = new { @class = "form-control" } })*@
                                @Html.TextAreaFor(model => model.en_content, new { id = "en_content", rows = "10", cols = "80" })
                                @Html.ValidationMessageFor(model => model.en_content, "", new { @class = "text-danger" })
                                @*<textarea name="editor1"></textarea>*@
                                <script>CKEDITOR.replace("en_content");</script>
                            </div>
                        </div>

                        <div class="form-group">
                            @Html.LabelFor(model => model.th_title, htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.EditorFor(model => model.th_title, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.th_title, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            @Html.LabelFor(model => model.th_content, htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.TextAreaFor(model => model.th_content, new { id = "th_content", rows = "10", cols = "80" })
                                @Html.ValidationMessageFor(model => model.th_content, "", new { @class = "text-danger" })
                                <script>CKEDITOR.replace("th_content");</script>

                            </div>
                        </div>

                        <div class="form-group">
                            <div class="col-md-offset-2 col-md-10">
                                <input type="submit" value="Create" class="btn btn-default" />
                            </div>
                        </div>
                    </div>
                }

                <div>
                    @Html.ActionLink("Back to List", "Index")
                </div>
                <!-- /.card-body -->
            </div>
            <!-- /.card -->
        </div>
        <!-- /.col -->
    </div>
    <!-- /.row -->
</section>

Views/question_category/Index.cshtml
@model IEnumerable<IMODA.Models.question_category>

@{
    ViewBag.Title = "Index";
}
<section class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
                <h1>Question Category</h1>
            </div>
        </div>
    </div><!-- /.container-fluid -->
</section>

<section class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
                <input type="button" class="btn btn-info btn-lg" value="新增" onclick="location.href='@Url.Action("Create", "question_category")'" />
            </div>
        </div>
    </div><!-- /.container-fluid -->
</section>

<section class="content">
    <div class="row">
        <div class="col-12">

            <!-- /.card -->

            <div class="card">
                @*<div class="card-header">
                        <h3 class="card-title">DataTable with default features</h3>
                    </div>*@
                <!-- /.card-header -->
                <div class="card-body">
                    @using (Html.BeginForm("Index", "question_category", FormMethod.Post))
                    {
                        <button type="submit" value="Delete" class="btn btn-sm btn-danger rounded-0" onclick="return confirm('Are you sure?')"><i class="fa fa-trash-o"></i> Delete</button>
                        <br /><br />
                        <table style="text-align:center;" id="example1" class="display">
                            <thead>
                                <tr>

                                    <th>@Html.DisplayNameFor(model => model.active)</th>
                                    <th>@Html.DisplayNameFor(model => model.th_title)</th>
                                    <th>@Html.DisplayNameFor(model => model.en_title)</th>
                                    <th>modify</th>
                                    <th>
                                        Delete <input type="checkbox" id="checkBoxAll" class="custom-checkbox" />
                                    </th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach (var item in Model)
                                {
                                <tr>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.active)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.th_title)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.en_title)
                                    </td>
                                    <td>
                                        @Html.ActionLink("modify", "Mod", new { id = item.id })
                                    </td>
                                    <td>
                                        <input type="checkbox" name="ID" value="@item.id" class="custom-checkbox chkCheckBoxId" />
                                    </td>
                                </tr>
                                }

                            </tbody>
                            <tfoot>
                                <tr>
                                    <th>@Html.DisplayNameFor(model => model.active)</th>
                                    <th>@Html.DisplayNameFor(model => model.th_title)</th>
                                    <th>@Html.DisplayNameFor(model => model.en_title)</th>
                                    <th>modify</th>
                                    <th>
                                        Delete 
                                    </th>
                                </tr>
                            </tfoot>
                        </table>
                    }
                </div>
                <!-- /.card-body -->
            </div>
            <!-- /.card -->
        </div>
        <!-- /.col -->
    </div>
    <!-- /.row -->
</section>
<!-- jQuery -->
<script src="~/plugins/jquery/jquery.min.js"></script>
<!-- Bootstrap 4 -->
<script src="../../plugins/bootstrap/js/bootstrap.bundle.min.js"></script>
<!-- DataTables -->
@*<script src="../../plugins/datatables/jquery.dataTables.min.js"></script>*@
<script src="../../plugins/datatables-bs4/js/dataTables.bootstrap4.min.js"></script>
<script src="../../plugins/datatables-responsive/js/dataTables.responsive.min.js"></script>
<script src="../../plugins/datatables-responsive/js/responsive.bootstrap4.min.js"></script>
<script type="text/javascript" src="https://cdn.datatables.net/1.10.21/js/jquery.dataTables.min.js"></script>

<!-- AdminLTE App -->
<script src="../../dist/js/adminlte.min.js"></script>
<!-- AdminLTE for demo purposes -->
<script src="../../dist/js/demo.js"></script>
<!-- page script -->
<script>
    $(document).ready(function () {
        $("#example1").DataTable({
            "paging": true,
            "responsive": true,
            "autoWidth": false,
            "ordering": true,
            "info": true,
            "responsive": true,
        });
        $('#checkBoxAll').click(function () {
            if ($(this).is(":checked")) {
                $(".chkCheckBoxId").prop("checked", true)
            }
            else {
                $(".chkCheckBoxId").prop("checked", false)
            }
        });
    });
</script>

Views/question_category/Mod.cshtml
@model IMODA.Models.question_category

@{
    ViewBag.Title = "Mod";
}

<section class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
                <h1>Question Category Management > Modify</h1>
            </div>
        </div>
    </div><!-- /.container-fluid -->
</section>


<section class="content">
    <div class="row">
        <div class="col-12">
            <!-- /.card -->
            <div class="card">
                @*<div class="card-header">
                        <h3 class="card-title">DataTable with default features</h3>
                    </div>*@
                <!-- /.card-header -->
                <div class="card-body">
                    @using (Html.BeginForm())
                    {
                        @Html.AntiForgeryToken()
                    <div class="form-horizontal">
                        @*<h4>Name</h4>*@
                        <hr />
                        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                        @Html.HiddenFor(model => model.id)




                        <div class="form-group">
                            @Html.LabelFor(model => model.active, htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.EditorFor(model => model.active, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.active, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            @Html.LabelFor(model => model.en_title, htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.EditorFor(model => model.en_title, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.en_title, "", new { @class = "text-danger" })
                            </div>
                        </div>
                        <div class="form-group">
                            @Html.LabelFor(model => model.en_content, htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.TextAreaFor(model => model.en_content, new { id = "en_content", rows = "10", cols = "80" })
                                @Html.ValidationMessageFor(model => model.en_content, "", new { @class = "text-danger" })
                                <script>CKEDITOR.replace("en_content");</script>
                            </div>
                        </div>
                        <div class="form-group">
                            @Html.LabelFor(model => model.th_title, htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.EditorFor(model => model.th_title, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.th_title, "", new { @class = "text-danger" })
                            </div>
                        </div>
                        <div class="form-group">
                            @Html.LabelFor(model => model.th_content, htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.TextAreaFor(model => model.th_content, new { id = "th_content", rows = "10", cols = "80" })
                                @Html.ValidationMessageFor(model => model.th_content, "", new { @class = "text-danger" })
                                <script>CKEDITOR.replace("th_content");</script>
                            </div>
                        </div>

                        <div class="form-group">
                            <div class="col-md-offset-2 col-md-10">
                                <input type="submit" value="Save" class="btn btn-default" />
                            </div>
                        </div>
                    </div>
                    }


                </div>
                <!-- /.card-body -->
            </div>
            <!-- /.card -->
        </div>
        <!-- /.col -->
    </div>
    <!-- /.row -->
</section>